# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)


Day.create( :title => 'Bellingham Downtown Day With Kids', :location => 'Bellingham, WA, USA', :latitude => '48.7595529', :longitude => '-122.4882249', :description => 'Start the day with a delicious breakfast from The Old Town Cafe. (http://www.theoldtowncafe.com/) Go to The Marine Life Center and touch sea stars, sea anomies, and other creatures (http://www.marinelifecenter.org/index.php) Follow this with kite flying, scooter riding, park playing, and a ...picnic at Zuanich Point Park (http://www.portofbellingham.com/Facilities.aspx?Page=detail&RID=11) Head indoors to The Whatcom Museum Lightcatcher Building and explore the children\'s area (http://www.whatcommuseum.org/home-page) If the kids haven\'t had a melt-down yet, head over to La Fiamma for some great wood fire pizza. The kids can play with dough while you wait for you food. (http://www.lafiamma.com/)')

 
Day.create( :title => 'Ryan\'s Yakima Wine Tasting Day with Kids', :location => 'Yakima, WA, USA', :latitude => '46.6020711', :longitude => '-120.5058987', :description => 'The Yakima Valley has well over 300 days of sunshine a year and lots of open spaces for families to play. As a result, this is a great place for growing wine grapes, apples, pumpkins, and families. One of our favorite activities outside is wine tasting, but our kids are still of an impre...ssionable age and aren\'t old enough to serve as designated drivers or drinkers. So, when we want to enjoy the local wineries we need to be selective. Bonair Winery (http://www.bonairwine.com/) is on the Rattlesnake Wine Trail outside of Zillah, WA. They are a family friendly winery where kids can feed the ducks, pet the dog or play with the small collection of toys that Bonair has always kept in the corner of their tasting room. If you are on this side of Union Gap, then visit this winery. They have great reds, legendary Chardonnay, and the friendliest atmosphere in the region. If you have to go to a second winery, and the kids haven\'t started whining too much themselves, then catch Wineglass Cellars (http://www.wineglasscellars.com/) just up the road from Bonair. Dave, in the tasting room of Wineglass can fill you with great wine and fill you in on the local bicycling scene. After wine tasting, head to Granger, WA just down I-82 from Zillah and catch dinosaur park. Each year since 1996 the city shop has built a new dinosaur statue in somewhere in town. For a small town like Granger, there is almost more pre-historic lizards than people. If you are on the north end of the Yakima Valley, then head to Cowiche Canyon Conservancy\'s trails off of Scenic Drive, or Cowiche Canyon Road. These trailheads take you on walks, runs or mt bike rides through preserved shrub steppe, east slope steelhead streams, and eventually to a great wine tasting room on the Andesite bluffs overlooking the Yakima and Naches Valleys. If you are visisting in the fall, take the kids to Naches\' Thompson Farm for pumpkin picking, pumpkin doughnuts, and pumkin cannon demonstrations. They usually have a lame corn maze too that the under 10 age group loves.')


Day.create( :title => 'Jeffrey\'s Day From Galbraith to Marine Park and Mallards', :location => 'Bellingham, WA, USA', :latitude => '48.7595529', :longitude => '-122.4882249', :description => 'Bellingham has the greatest trails. My perfect day would begin at Galbraith Mountain. The mountain has an elaborate system of trails, for all abilities and the views from the Ridge trail, Wonderland trail, and Woopsie Woodle are amazing on a clear day. On a snowy or rainy day the dark forest with huge trees covered in mos...s and lichen along the Lost Giants trail makes me feel happy and rejuvenated. I often run these trails, but they are excellent for hiking, and well known to mountain bikers. Maps are available at local running and bike stores, and you\'ll definitely want one along. If you go in the morning, you will often be alone, or see only a few folks.
After returning from a morning run (or hike), I would go the Little Cheerful Cafe on the corner of Holly and Railroad. Their breakfast hash browns and eggs benedict with endless cups of coffee will definitely fill you up, and you\'ll very likely need a nap in the sun afterwards.
Just a short walk down Holly Street, at the bottom of the hill is Maritime Heritage Park. The park has a fish hatchery, salmon ladder and a huge waterfall. It\'s an amazing place to take visitors who have never seen salmon spawning, because you can see the whole process. The ocean (saltwater) comes almost to the base of waterfall, and you can watch as the fish jump up the ladder to try to get upstream. The hatchery has interpretive signs explaining the finer details of the process. There\'s also a nice amphitheater with warm concrete benches and a view of the bay to snooze off your big breakfast.
Just a block down the street is the best maritime junk store on the planet, the Marine Exchange. I can spend hours here, but even the least boat-savvy person will enjoy a few minutes looking at all the second-hand boat equipment and maritime art here. On the floor, just inside the entry is the pile of the newest consignment items, ready to be pawed through, and often the prices haven\'t been set so you can score a great deal. Don\'t miss the basement, which is stacked floor to ceiling with even more stuff.
Towards dinner time, it would be worth a trip to Blue Fin Sushi on Samish Way. They have a selection of maki rolls on their menu that will amaze anyone. They also have a number of seasonal fish selections, and when sockeye is on the list you need to order it. Its bright red and super tasty and is best enjoyed as sushi and not complicated with other flavors in a maki roll.
Leave a little room for a stop at Mallard Ice Cream on Railroad Ave on your way home. You\'ll want to try a fudge-dipped cone: they pour a scoop of hot fudge in a waffle cone and put the ice cream over the top of it. It has the flavor of a sundae in the cone. It\'ll give you the calories you need to do it all again tomorrow.')

Day.create( :title => 'Kieran\'s Orcas Island Day', :location => 'Orcas Island, Orcas, WA, USA', :latitude => '48.6597887', :longitude => '-122.8457029', :description => 'On a nice summer day camp at Moran state park (http://www.parks.wa.gov/parks/?selectedpark=Moran) on Orcas Island, make sure to reserve a site located on the shores on one of the two crystal clear lakes. Take a kayak to fish in Mountain Lake in the morning. If you need a kayak, here is a list of rental and kayak tour businesses on Orcas: (http://www.sanjuanislandsdirectory.com/orcas/okayak.htm) Come in and cook breakfast, then go on a nice bike ride around the island to get lunch and coffee in Eastsound. Then ride bike back to the campsite. Then go on a drive with the kayak to deer harbor. Kayak around the harbor and various islands located near by. Kayak back in and get ice cream at the harbor store. Drive back to Eastsound and have dinner at the Inn at Ship Bay (http://www.innatshipbay.com/) during sunset. End the day with a campfire and smores!')

